# Generated by Django 5.1.7 on 2025-03-27 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('ikoyi', 'Ikoyi'), ('vi', 'Victoria Island')], max_length=20)),
                ('property_type', models.CharField(choices=[('shortlet', 'Shortlet'), ('investment', 'Investment'), ('hybrid', 'Hybrid')], max_length=20)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('investment_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('roi_percentage', models.FloatField(blank=True, null=True)),
                ('commission_percentage', models.FloatField(default=5.0)),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated list')),
                ('images', models.JSONField(default=list, help_text='List of image URLs')),
                ('virtual_tour_url', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listed_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
