# Generated by Django 5.1.7 on 2025-03-27 09:40

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_id', models.FileField(upload_to=core.models.user_directory_path)),
                ('cac_certificate', models.FileField(upload_to=core.models.user_directory_path)),
                ('business_proof', models.FileField(upload_to=core.models.user_directory_path)),
                ('authorization_letter', models.FileField(upload_to=core.models.user_directory_path)),
                ('is_verified', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
