# Generated by Django 5.1.7 on 2025-03-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='property',
            new_name='gifted_property',
        ),
    ]
