# Generated by Django 5.1.7 on 2025-03-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='available_to',
            field=models.CharField(choices=[('all', 'All Users'), ('members', 'Private Members Only')], default='all', max_length=10),
        ),
    ]
