# Generated by Django 5.1.2 on 2025-03-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_message_conversation_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentverification',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='agentverification',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('verified', 'Verified')], default='unverified', max_length=20),
        ),
    ]
