# Generated by Django 5.1.2 on 2025-03-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_agentverification_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='proof_of_listing',
            field=models.URLField(blank=True, null=True),
        ),
    ]
