# Generated by Django 5.1.2 on 2025-03-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_investment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
