from django.urls import path

from .views import (
    RegisterView,
    LoginView,
    ProfileView,
    AgentVerificationView,
    BookingView,
    CreateGiftView,
    RespondToGiftView,
    ReassignGiftView,
    CreateAdminView,
    CancelBookingView,
    UpdateBookingView,
    WithdrawalRequestView,
    WalletView,
    AdminGiftListView,
    InvestmentView,
    ROIPayoutCreateView,
    InvestorROIPayoutListView,
    ROIGrowthChartView,
    InvestmentROIPayoutHistoryView,
    MyMembershipView,
    CreateReviewView,
    AgentReviewListView,
    PropertyReviewListView,
    UserNotificationsView,
    MarkNotificationReadView,
    ToggleFavoriteView,
    MyFavoritesView,
    SwitchRoleView,
    MyInstallmentsView,
    MarkInstallmentPaidView,
    WalletTransactionHistoryView,
    PropertyBookingCalendarView,
    GrantSilverMembershipView,
    UserDashboardView,
    UserProfileUpdateView,
    ChangePasswordView,
    MembershipPortalView,
    AgentVerificationStatusView,
    AgentMetricsView,
    AgentWithdrawalListView,
    InitiateGiftPaymentView,
    VerifyGiftPaymentView,
    InitiateBookingPaymentView,
    VerifyBookingPaymentView,
    public_user_profile,
    InitiateInvestmentPaymentView,
    VerifyInvestmentPaymentView
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('verify-agent/', AgentVerificationView.as_view(), name='verify-agent'),
    path('book/', BookingView.as_view(), name='book-property'),
    path('create-admin/', CreateAdminView.as_view(), name='create-admin'),
    path('cancel-booking/<int:booking_id>/', CancelBookingView.as_view(), name='cancel-booking'),
    path('update-booking/<int:booking_id>/', UpdateBookingView.as_view(), name='update-booking'),
    path('withdraw-request/', WithdrawalRequestView.as_view(), name='withdraw-request'),
    path('wallet/', WalletView.as_view(), name='wallet'),
    path('gift/create/', CreateGiftView.as_view(), name='gift-create'),
    path('gift/respond/', RespondToGiftView.as_view(), name='gift-respond'),
    path('gift/reassign/', ReassignGiftView.as_view(), name='gift-reassign'),
    path('gift/all/', AdminGiftListView.as_view(), name='admin-gift-list'),
    path('invest/', InvestmentView.as_view(), name='invest'),
    path('roi/log/', ROIPayoutCreateView.as_view(), name='log-roi'),
    path('roi/my/', InvestorROIPayoutListView.as_view(), name='my-roi'),
    path('roi/chart/', ROIGrowthChartView.as_view(), name='roi-chart'),
    path('roi/investment/<int:investment_id>/', InvestmentROIPayoutHistoryView.as_view(), name='investment-roi-history'),
    path('membership/', MyMembershipView.as_view(), name='my-membership'),
    path('reviews/create/', CreateReviewView.as_view(), name='create-review'),
    path('reviews/property/<int:property_id>/', PropertyReviewListView.as_view(), name='property-reviews'),
    path('reviews/agent/<int:agent_id>/', AgentReviewListView.as_view(), name='agent-reviews'),
    path('notifications/', UserNotificationsView.as_view(), name='notifications'),
    path('notifications/<int:notification_id>/read/', MarkNotificationReadView.as_view(), name='mark-notification-read'),
    path('favorites/toggle/', ToggleFavoriteView.as_view(), name='toggle-favorite'),
    path('favorites/my/', MyFavoritesView.as_view(), name='my-favorites'),
    path('user/switch-role/', SwitchRoleView.as_view(), name='switch-role'),
    path('installments/my/', MyInstallmentsView.as_view(), name='my-installments'),
    path('installments/<int:installment_id>/mark-paid/', MarkInstallmentPaidView.as_view(), name='mark-installment-paid'),
    path('wallet/transactions/', WalletTransactionHistoryView.as_view(), name='wallet-transactions'),
    path('calendar/<int:property_id>/', PropertyBookingCalendarView.as_view(), name='property-calendar'),
    path('membership/subscribe/', GrantSilverMembershipView.as_view(), name='subscribe-silver'),
    path('dashboard/', UserDashboardView.as_view(), name='user-dashboard'),
    path('profile/update/', UserProfileUpdateView.as_view(), name='user-profile'),
    path('profile/change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('membership/portal/', MembershipPortalView.as_view(), name='membership-portal'),
    path('agent/verification-status/', AgentVerificationStatusView.as_view()),
    path('agent/metrics/', AgentMetricsView.as_view(), name='agent-metrics'),
    path('agent/withdrawals/', AgentWithdrawalListView.as_view(), name='agent-withdrawals'),
    path('gift/initiate-payment/', InitiateGiftPaymentView.as_view(), name='gift-initiate-payment'),
    path('gift/verify-payment/', VerifyGiftPaymentView.as_view(), name='gift-verify-payment'),
    path('booking/initiate-payment/', InitiateBookingPaymentView.as_view(), name='initiate-book'),
    path('booking/verify-payment/', VerifyBookingPaymentView.as_view(), name='booking-verify-payment'),
    path('users/<int:user_id>/', public_user_profile, name='public_user_profile'),
    path('invest/initiate-payment/', InitiateInvestmentPaymentView.as_view(), name='invest-initiate-payment'),
    path('invest/verify-payment/', VerifyInvestmentPaymentView.as_view(), name='invest-verify-payment'),
]

